### ISSUE TITLE
Debug logging appears to console even though debug=False

### ISSUE THREAD

**Issue by patrijuh** [Hi-Fi/robotframework-httprequestlibrary#39]
Using robotframework-maven-plugin 1.4.7 and robotframework-httprequestlibrary 0.0.9

In our tests, we are creating sessions with debug=False, example:

Create Session	${SESSION_NAME}  ${SERVICE-URL}  headers=${headers}  debug=False

Still there appears a lot of these debug log writings to console when we execute the tests:

*DEBUG* Connection manager is shutting down
*DEBUG* Connection manager is shutting down
*DEBUG* Connection manager shut down
*DEBUG* Connection manager is shutting down
*DEBUG* Connection manager shut down
*DEBUG* Connection manager is shutting down
*DEBUG* Connection manager shut down
*DEBUG* Connection manager is shutting down
*DEBUG* Connection manager shut down

**Comment by Hi-Fi** [comment]
Thank you, I have to rethink the logging also with the HTTPclient. 
There's 2 issues actually:
1. Some messages "bypass" robot context, and print the messages to stdout (even should go to Robot's log)
2. The log level setting to HTTP client seems for some reason getting DEBUG even it's not enabled.

**Comment by Hi-Fi** [comment]
Fixed in version 0.0.10, which should be available in Maven central shortly
