### ISSUE TITLE
Setting the logging to jcl causing issue with using applications with slf4j

### ISSUE THREAD

**Issue by anilkbachola** [Hi-Fi/robotframework-httprequestlibrary#41]
Issue with setting below system property in the library initialization
System.setProperty("org.apache.commons.logging.Log", "com.github.hi_fi.httprequestlibrary.utils.RobotLogger")

1. As part of integration tests I am launching an application in its isolation .i.e having a separate class child-first loader to start my application
2. As the logging is getting initialized and set to 'RobotLogger' when my application starts, it is throwing ClassNotFoundException. as the 'RobotLogger' is not part of my application classpath.

**Comment by Hi-Fi** [comment]
I think I have to check this. At least the HTTPclient logging are not coming to logs if this logger is not set.
