### ISSUE TITLE
Running tests from standalone JAR with this module

### ISSUE THREAD

**Issue by ppazos** [Hi-Fi/robotframework-httprequestlibrary#45]
I'm new to robot in general, and I I'm trying to test this module but getting: No module named HttpRequestLibrary

Tried:

java -cp "./robotframework-httprequestlibrary-0.0.13-jar-with-dependencies.jar" -jar robotframework-3.1.1.jar mytests.robot

Can you point me out where the error is? Thanks!

**Comment by Hi-Fi** [comment]
Seems that the jar-with-dependencies is incorrectly build (same way as it's incorrectly build with https://github.com/Hi-Fi/robotframework-seleniumlibrary-java). Currently RF is actually missing from the "with-deps" -jar, so running requires RF and robotframework-httprequestlibrary-0.0.13-jar-with-dependencies jars both. With those running happens with:
`java -cp robotframework-3.1.1.jar;robotframework-httprequestlibrary-0.0.13-jar-with-dependencies.jar org.robotframework.RobotFramework <path to testcases>` 

I'll fix the bug with packaging.

**Comment by Hi-Fi** [comment]
Jar creation fixed in 0.0.14, which should be quite quickly at Maven central.
