### ISSUE TITLE
Keyword documentation link on readme is dead

### ISSUE THREAD

**Issue by ppazos** [Hi-Fi/robotframework-httprequestlibrary#47]

**Comment by Hi-Fi** [comment]
Link points to Maven central directly, and starts to work when release is published there (takes some time).

At the meantime documentation from previous tagged version is usable, especially as there was no functional changes in new release. 

Previous documentation at https://repo1.maven.org/maven2/com/github/hi-fi/robotframework-httprequestlibrary/0.0.13/robotframework-httprequestlibrary-0.0.13.html.

**Comment by ppazos** [comment]
@Hi-Fi now it is working, before I received 404
