### ISSUE TITLE
Not possible to send a dictionary inside list  in POST request payload

### ISSUE THREAD

**Issue by patrijuh** [Hi-Fi/robotframework-httprequestlibrary#48]
${dict}=  Create Dictionary  clientRole=true  composite=false containerId=${userid}  id=${roleid}
 @{list}=  Create List  ${dict}

  ${response}=  Post Request  ${KEYCLOAK-SERVICE-NAME}  uri=xxxxx/xxxx  data=${list}

Leads to an error java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 3 path $[0]

Does not work either when trying to give the payload as string:

${data_string}=  Set Variable  [{"id": "${roleid}","name": "${rolename}", "scopeParamRequired": "false"}]
${response}=  Post Request  ${KEYCLOAK-SERVICE-NAME}  uri=xxxxx/xxxx  data=${data_string}

**Comment by patrijuh** [comment]
With python requests library (https://github.com/bulkan/robotframework-requests) the same works perfectly.

**Comment by patrijuh** [comment]
Any progress on this?

**Comment by Hi-Fi** [comment]
The error message pasted probably comes from json parsing, that library (GSon) fails to do. But hard to say with just that.

Also the question remains, what is expected to be sent? At least when I tried with latest Robot, the example fails with: `ValueError: too many values to unpack (expected 2)` (from `Post Request`) keyword.

**Comment by viitaell** [comment]
To specify why this is the way the data is sent:
As making these steps manually you can see that the way the request is made:
[{"id":"role-id","name":"rolename","scopeParamRequired":false,"composite":false,"clientRole":true,"containerId":"id"}]
https://www.keycloak.org/docs-api/3.0/rest-api/index.html#_client_role_mappings_resource 
Keycloak rest API documentation 
RequestsLibrary works: 
${response} = RequestsLibrary . Post Request ${keycloak} 
 uri=/  headers=${headers}  data=${list}

**Comment by Hi-Fi** [comment]
Fixed at 0.0.15
