### ISSUE TITLE
TypeError: <java function runKeyword 0x2> is not a Python function with robot framework 3.1.1

### ISSUE THREAD

**Issue by dnekhayev** [Hi-Fi/robotframework-httprequestlibrary#50]
I tried to run Get.robot within my own jar. This issue is not reproduced with a build against RF 2.8.7
[ ERROR ] Adding keyword 'optionsRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'getJsonResponse' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'toJson' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'prettyPrintJson' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'getResponseStatusCode' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'getRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'responseCodeShouldBe' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'responseShouldContain' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'putRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'deleteRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'postRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'headRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'createSession' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'createDigestSession' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ ERROR ] Adding keyword 'patchRequest' to library 'HttpRequestLibrary' failed: TypeError: <java function runKeyword 0x2> is not a Python function
[ WARN ] Imported library 'HttpRequestLibrary' contains no keywords.

**Comment by dnekhayev** [comment]
Java 12 / Windows - doesn't work
Java 11 / Windows & Linux - works
Java 8 / Windows - works

**Comment by Hi-Fi** [comment]
I actually haven't tested this at all with Java 12 (only used with Java 8), so there might be issues with that.

**Comment by dnekhayev** [comment]
Probably it's needed to rebuild RF 3.1.1 with Java 12. Closing the issue since it's not related to Http Request Library. isfunction() method from inspect.py gives unexpected result.
